Name:           ros-hydro-strands-morse
Version:        0.0.6
Release:        0%{?dist}
Summary:        ROS strands_morse package

Group:          Development/Libraries
License:        BSD
URL:            http://www.strands-project.eu
Source0:        %{name}-%{version}.tar.gz

Requires:       opencv-python
Requires:       pcl
Requires:       pcl-tools
Requires:       ros-hydro-cv-bridge
Requires:       ros-hydro-message-filters
Requires:       ros-hydro-opencv2
Requires:       ros-hydro-pcl-ros
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rospy
Requires:       ros-hydro-scitos-description
Requires:       ros-hydro-scitos-msgs
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-tf
Requires:       ros-hydro-topic-republisher
BuildRequires:  opencv-python
BuildRequires:  pcl-devel
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-cv-bridge
BuildRequires:  ros-hydro-message-filters
BuildRequires:  ros-hydro-opencv2
BuildRequires:  ros-hydro-pcl-ros
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-tf

%description
The strands_morse package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Nov 04 2014 Marc Hanheide <marc@hanheide.net> - 0.0.6-0
- Autogenerated by Bloom

* Thu Oct 30 2014 Marc Hanheide <marc@hanheide.net> - 0.0.5-0
- Autogenerated by Bloom

* Wed Sep 10 2014 Marc Hanheide <marc@hanheide.net> - 0.0.3-1
- Autogenerated by Bloom

* Thu Sep 04 2014 Marc Hanheide <marc@hanheide.net> - 0.0.3-0
- Autogenerated by Bloom

